#!/bin/bash
ls -lah /config /config/startup-config /config/data

if [ -f /config/startup-config/habridge.config ]; then
  echo -e "Copy over config"
  cp /config/startup-config/* /config/data/
fi

ADDPARAM="-Dupnp.config.address=$SERVERIP -Dserver.port=$SERVERPORT -Dsecurity.key=$SECKEY"
echo -e "Parameters used:\nServer IP : $SERVERIP\nServer Port : $SERVERPORT"

echo "Starting Home Automation Bridge"
java -jar $ADDPARAM /usr/local/bin/ha-bridge.jar 2>&1 | tee /config/data/ha-bridge.log
